apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}-config
data:
  PUID: "{{ .Values.mariadb.env.PUID }}"
  PGID: "{{ .Values.mariadb.env.PGID }}"
  TZ: "{{ .Values.mariadb.env.TZ }}"
  MYSQL_DATABASE: "{{ .Values.mariadb.env.MYSQL_DATABASE }}"
  MYSQL_USER: "{{ .Values.mariadb.env.MYSQL_USER }}"
