apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bookstack.fullname" . }}-config
data:
  PUID: "{{ .Values.bookstack.env.PUID }}"
  PGID: "{{ .Values.bookstack.env.PGID }}"
  TZ: "{{ .Values.bookstack.env.TZ }}"
  APP_URL: "{{ .Values.bookstack.env.APP_URL }}"
