apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-bookstack-to-mariadb
spec:
  podSelector:
    matchLabels:
      app: {{ include "bookstack.fullname" . }}
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mariadb
      ports:
        - protocol: TCP
          port
