apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mariadb.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.pvc.size }}
