apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bookstack.fullname" . }}-secrets
type: Opaque
data:
  APP_KEY: {{ .Values.bookstack.env.APP_KEY | b64enc | quote }}
  DB_PASSWORD: {{ .Values.bookstack.env.DB_PASSWORD | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.bookstack.env.MAIL_PASSWORD | b64enc | quote }}
