apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.env.MYSQL_ROOT_PASSWORD | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mariadb.env.MYSQL_PASSWORD | b64enc | quote }}
