apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}
spec:
  selector:
    app: {{ include "mariadb.fullname" . }}
  ports:
    - port: 3306
      targetPort: {{ .Values.mariadb.port }}
