apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookstack.fullname" . }}
spec:
  selector:
    app: {{ include "bookstack.fullname" . }}
  ports:
    - port: 80
      targetPort: {{ .Values.bookstack.port }}
