apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstack-db
spec:
  serviceName: bookstack-db
  replicas: 1
  selector:
    matchLabels:
      app: bookstack-db
  template:
    metadata:
      labels:
        app: bookstack-db
    spec:
      containers:
        - name: mariadb
          image: lscr.io/linuxserver/mariadb
          ports:
            - containerPort: 3306
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: mariadb-config
                  key: PUID
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: mariadb-config
                  key: PGID
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: mariadb-config
                  key: TZ
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mariadb-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mariadb-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/mysql
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: [ "mysqladmin", "ping", "-h", "localhost" ]
            initialDelaySeconds: 10
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: db-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
