apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstack-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/bookstack/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
