image: lscr.io/linuxserver/bookstack
tag: latest
port: 80

env:
  PUID: "1000"
  PGID: "1000"
  TZ: "Etc/UTC"
  APP_URL: "https://bookstack.edusuc.net"

ingress:
  enabled: true
  host: bookstack.edusuc.net
  tls: true
  tlsSecretName: bookstack-tls

pvc:
  size: 1Gi
