apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mariadb-from-bookstack
spec:
  podSelector:
    matchLabels:
      app: {{ include "mariadb.fullname" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: bookstack
      ports:
        - protocol: TCP
          port: 3306
